export type DateCategory =
  | "first-date"
  | "anniversary"
  | "nature"
  | "gastronomy"
  | "winter"
  | "adventure"
  | "art-culture";

export type City = "Montréal" | "Laval" | "Brossard" | "Magog";
export type CardVariant = "rose" | "gold" | "dark";

export type DateOccasion =
  // Singles
  | "1ere-date"
  | "2eme-date"
  | "3eme-date+"
  | "casual"
  // Couples
  | "date-night"
  | "anniversaire"
  | "saint-valentin"
  | "birthday"
  // Both
  | "weekend";

export type Season = "printemps" | "ete" | "automne" | "hiver" | "all";

export type DateIdea = {
  id: string;
  title: string;
  category: DateCategory;
  city: City;
  occasions: DateOccasion[];
  seasons: Season[];
  steps: string[];
  duration: string;
  price: string;
  rating: number;
  ratingCount: number;
  variant: CardVariant;
  forSingles: boolean;
  forCouples: boolean;
};

export const CATEGORIES: { value: DateCategory; label: string; emoji: string }[] = [
  { value: "art-culture", label: "Art & Culture", emoji: "🎨" },
  { value: "gastronomy", label: "Gastronomie", emoji: "🍷" },
  { value: "nature", label: "Nature & Plein air", emoji: "🌿" },
  { value: "adventure", label: "Aventure", emoji: "🎯" },
  { value: "winter", label: "Hiver", emoji: "❄️" },
  { value: "anniversary", label: "Anniversaire", emoji: "💍" },
  { value: "first-date", label: "1ères dates", emoji: "🌹" },
];

export const DATES: DateIdea[] = [
  {
    id: "cafe-mont-royal",
    title: "Café & Mont-Royal",
    category: "nature",
    city: "Montréal",
    occasions: ["1ere-date", "2eme-date", "casual"],
    seasons: ["printemps", "ete", "automne"],
    steps: [
      "Café spécialité dans le Plateau",
      "Marche jusqu'au Mont-Royal",
      "Belvédère & panorama de Montréal",
    ],
    duration: "3h",
    price: "~$25/pers.",
    rating: 4.7,
    ratingCount: 543,
    variant: "rose",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "brunch-galerie",
    title: "Brunch & Galerie",
    category: "art-culture",
    city: "Montréal",
    occasions: ["1ere-date", "casual", "date-night"],
    seasons: ["all"],
    steps: [
      "Brunch dans le Mile End",
      "Visite d'une galerie d'art locale",
      "Café artisanal pour conclure",
    ],
    duration: "4h",
    price: "~$55/pers.",
    rating: 4.7,
    ratingCount: 234,
    variant: "gold",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "musee-cafe",
    title: "Musée & Café",
    category: "art-culture",
    city: "Montréal",
    occasions: ["1ere-date", "casual"],
    seasons: ["all"],
    steps: [
      "Visite du Musée des Beaux-Arts",
      "Discussion devant les œuvres",
      "Café & dessert pour conclure",
    ],
    duration: "3-4h",
    price: "~$45/pers.",
    rating: 4.6,
    ratingCount: 312,
    variant: "dark",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "escape-cocktails",
    title: "Escape Room & Cocktails",
    category: "adventure",
    city: "Montréal",
    occasions: ["1ere-date", "2eme-date"],
    seasons: ["all"],
    steps: [
      "Escape room thématique 60 min",
      "Debrief autour de cocktails signés",
      "Resto tapas optionnel",
    ],
    duration: "3–4h",
    price: "~$70/pers.",
    rating: 4.7,
    ratingCount: 234,
    variant: "rose",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "marche-jean-talon",
    title: "Marché & Brunch",
    category: "gastronomy",
    city: "Montréal",
    occasions: ["2eme-date", "casual", "weekend"],
    seasons: ["printemps", "ete", "automne"],
    steps: [
      "Tour du Marché Jean-Talon",
      "Dégustation chez les producteurs",
      "Brunch dans la Petite-Italie",
    ],
    duration: "4h",
    price: "~$40/pers.",
    rating: 4.8,
    ratingCount: 421,
    variant: "gold",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "comedie-cocktails",
    title: "Comédie & Cocktails",
    category: "art-culture",
    city: "Montréal",
    occasions: ["2eme-date", "date-night"],
    seasons: ["all"],
    steps: [
      "Spectacle de stand-up au Bordel ou Comedy Nest",
      "Cocktails dans le Vieux-Mtl",
      "Marche romantique au Vieux-Port",
    ],
    duration: "4h",
    price: "~$75/pers.",
    rating: 4.6,
    ratingCount: 187,
    variant: "dark",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "patin-vieux-port",
    title: "Patin & Chocolat",
    category: "winter",
    city: "Montréal",
    occasions: ["1ere-date", "2eme-date", "date-night"],
    seasons: ["hiver"],
    steps: [
      "Patinage au Vieux-Port",
      "Pause chocolat chaud",
      "Balade dans le Vieux-Mtl",
    ],
    duration: "3h",
    price: "~$35/pers.",
    rating: 4.5,
    ratingCount: 421,
    variant: "rose",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "karting-fondue",
    title: "Karting & Fondue",
    category: "adventure",
    city: "Brossard",
    occasions: ["2eme-date", "date-night", "casual"],
    seasons: ["all"],
    steps: [
      "Sessions de karting indoor",
      "Trophée à celui qui gagne 😉",
      "Fondue chinoise pour célébrer",
    ],
    duration: "4h",
    price: "~$85/pers.",
    rating: 4.5,
    ratingCount: 156,
    variant: "gold",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "cours-cuisine",
    title: "Cours de cuisine privé",
    category: "gastronomy",
    city: "Laval",
    occasions: ["3eme-date+", "date-night", "anniversaire"],
    seasons: ["all"],
    steps: [
      "Cours de cuisine avec un chef",
      "Préparation d'un menu 3 services",
      "Dégustation à deux à la maison",
    ],
    duration: "4h",
    price: "~$110/pers.",
    rating: 4.8,
    ratingCount: 92,
    variant: "rose",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "vignoble-spa",
    title: "Vignoble & Spa",
    category: "gastronomy",
    city: "Magog",
    occasions: ["anniversaire", "saint-valentin", "date-night", "weekend"],
    seasons: ["printemps", "ete", "automne"],
    steps: [
      "Dégustation de vins en après-midi",
      "Balade dans les vignes",
      "Soirée spa & souper romantique",
    ],
    duration: "5–6h",
    price: "~$140/pers.",
    rating: 4.8,
    ratingCount: 312,
    variant: "gold",
    forSingles: false,
    forCouples: true,
  },
  {
    id: "coucher-soleil",
    title: "Coucher de soleil",
    category: "gastronomy",
    city: "Laval",
    occasions: ["anniversaire", "saint-valentin", "birthday"],
    seasons: ["printemps", "ete", "automne"],
    steps: [
      "Bouquet surprise livré",
      "Point de vue panoramique au coucher du soleil",
      "Dîner gastronomique réservé",
    ],
    duration: "4–5h",
    price: "~$180/pers.",
    rating: 4.9,
    ratingCount: 198,
    variant: "dark",
    forSingles: false,
    forCouples: true,
  },
  {
    id: "spa-nordique",
    title: "Spa Nordique",
    category: "gastronomy",
    city: "Brossard",
    occasions: ["anniversaire", "saint-valentin", "date-night"],
    seasons: ["hiver", "automne"],
    steps: [
      "Bains chauds & froids alternés",
      "Massage en duo",
      "Soirée tisane & feu de bois",
    ],
    duration: "Demi-journée",
    price: "~$140/pers.",
    rating: 4.9,
    ratingCount: 178,
    variant: "rose",
    forSingles: false,
    forCouples: true,
  },
  {
    id: "lac-chalet",
    title: "Lac & Chalet",
    category: "nature",
    city: "Magog",
    occasions: ["weekend", "anniversaire", "saint-valentin"],
    seasons: ["ete", "automne"],
    steps: [
      "Kayak sur le Memphrémagog",
      "Pique-nique au bord de l'eau",
      "Feu de camp & étoiles",
    ],
    duration: "Journée",
    price: "~$95/pers.",
    rating: 4.6,
    ratingCount: 87,
    variant: "gold",
    forSingles: false,
    forCouples: true,
  },
  {
    id: "cidrerie-automne",
    title: "Cidrerie & Pommes",
    category: "nature",
    city: "Magog",
    occasions: ["casual", "date-night", "weekend", "2eme-date"],
    seasons: ["automne"],
    steps: [
      "Cueillette de pommes en verger",
      "Dégustation de cidres locaux",
      "Tarte chaude & crème fraîche",
    ],
    duration: "5h",
    price: "~$45/pers.",
    rating: 4.6,
    ratingCount: 67,
    variant: "rose",
    forSingles: true,
    forCouples: true,
  },
  // ─── Huîtres à 1$ à Laval — promos en cours ─────────────
  {
    id: "huitres-gatto-matto",
    title: "Huîtres à 1$ · Gatto Matto",
    category: "gastronomy",
    city: "Laval",
    occasions: ["2eme-date", "date-night", "casual"],
    seasons: ["all"],
    steps: [
      "Jeudi dès 17h · 1950 rue Claude-Gagné #302, Laval",
      "Douzaines d'huîtres à 1$ + verre à partager",
      "Ambiance italienne chic près de Place Bell",
    ],
    duration: "1–2h",
    price: "~$25–40/pers.",
    rating: 4.7,
    ratingCount: 118,
    variant: "gold",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "huitres-mme-bovary",
    title: "Huîtres à 1$ · Mme Bovary",
    category: "gastronomy",
    city: "Laval",
    occasions: ["2eme-date", "date-night", "weekend"],
    seasons: ["all"],
    steps: [
      "Jeudi 17h à 22h · 1780 av. Pierre-Péladeau, Laval",
      "Douzaines d'huîtres fraîches à 1$",
      "Vibe bistro français au cœur du Centropolis",
    ],
    duration: "2h",
    price: "~$30–50/pers.",
    rating: 4.8,
    ratingCount: 156,
    variant: "rose",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "huitres-boating-club",
    title: "Huîtres à 1$ · Le Boating Club",
    category: "gastronomy",
    city: "Laval",
    occasions: ["date-night", "weekend", "casual"],
    seasons: ["all"],
    steps: [
      "Dimanche dès 17h · 30 boul. Curé-Labelle (Sainte-Rose)",
      "Douzaines d'huîtres à 1$ vue sur l'eau",
      "Cocktails et ambiance yacht club",
    ],
    duration: "2h",
    price: "~$30–45/pers.",
    rating: 4.6,
    ratingCount: 97,
    variant: "dark",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "huitres-lucilles",
    title: "Huîtres à 1$ · Lucille's",
    category: "gastronomy",
    city: "Laval",
    occasions: ["1ere-date", "2eme-date", "casual", "date-night"],
    seasons: ["all"],
    steps: [
      "Tous les jours · 2565 boul. Daniel-Johnson (Carrefour Laval)",
      "Douzaines d'huîtres à 1$ à toute heure",
      "Menu de mer complet si vous avez encore faim",
    ],
    duration: "1–2h",
    price: "~$25–40/pers.",
    rating: 4.5,
    ratingCount: 234,
    variant: "rose",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "huitres-vertigo",
    title: "Huîtres à 1$ · Vertigo",
    category: "gastronomy",
    city: "Laval",
    occasions: ["1ere-date", "2eme-date", "casual"],
    seasons: ["all"],
    steps: [
      "Lundi au jeudi 17h à 19h · côté bar seulement",
      "1880 av. Pierre-Péladeau (Centropolis)",
      "Huîtres à 1$ + cocktails signature",
    ],
    duration: "1–1h30",
    price: "~$25–35/pers.",
    rating: 4.7,
    ratingCount: 189,
    variant: "gold",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "huitres-123-dzo",
    title: "Huîtres à 1$ · 123 Dzô",
    category: "gastronomy",
    city: "Laval",
    occasions: ["2eme-date", "date-night", "casual"],
    seasons: ["all"],
    steps: [
      "Mardi et mercredi dès 17h · 2121 boul. le Carrefour, Laval",
      "Douzaines d'huîtres à 1$",
      "Cuisine asiatique fusion, cocktails créatifs",
    ],
    duration: "1–2h",
    price: "~$30–45/pers.",
    rating: 4.6,
    ratingCount: 142,
    variant: "dark",
    forSingles: true,
    forCouples: true,
  },
  // ==========================================================
  // Nouvelles idées Montréal (issues du catalogue GetYourGuide)
  // ==========================================================
  {
    id: "croisiere-brunch-fleuve",
    title: "Croisière brunch sur le fleuve",
    category: "gastronomy",
    city: "Montréal",
    occasions: ["date-night", "weekend", "anniversaire"],
    seasons: ["printemps", "ete", "automne"],
    steps: [
      "Départ du Vieux-Port de Montréal",
      "Brunch complet servi à bord (fromages, viennoiseries, chaud)",
      "2 h 30 sur le Saint-Laurent avec vue sur la skyline",
    ],
    duration: "2h30",
    price: "~$100/pers.",
    rating: 4.2,
    ratingCount: 379,
    variant: "gold",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "bateau-mouche-touristique",
    title: "Bateau-Mouche · croisière touristique",
    category: "nature",
    city: "Montréal",
    occasions: ["1ere-date", "casual", "weekend"],
    seasons: ["printemps", "ete", "automne"],
    steps: [
      "Bateau vitré depuis le Vieux-Port",
      "Commentaires en français sur l'histoire de Montréal",
      "1 à 1 h 30 avec vue panoramique",
    ],
    duration: "1–1h30",
    price: "~$45/pers.",
    rating: 4.0,
    ratingCount: 2066,
    variant: "rose",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "spa-nordique-thermal",
    title: "Expérience thermale nordique",
    category: "anniversary",
    city: "Montréal",
    occasions: ["date-night", "anniversaire", "saint-valentin"],
    seasons: ["all"],
    steps: [
      "Circuit chaud-froid-repos (bassins, saunas, vapeur)",
      "Journée complète en silence, aires de repos avec foyer",
      "Idéal en couple, ambiance zen imposée",
    ],
    duration: "Journée",
    price: "~$92/pers.",
    rating: 4.7,
    ratingCount: 475,
    variant: "dark",
    forSingles: false,
    forCouples: true,
  },
  {
    id: "musee-illusions",
    title: "Musée des illusions",
    category: "art-culture",
    city: "Montréal",
    occasions: ["1ere-date", "2eme-date", "casual"],
    seasons: ["all"],
    steps: [
      "Illusions d'optique et salles interactives",
      "Photos décalées à faire en duo",
      "1 h max — parfait à combiner avec un souper après",
    ],
    duration: "1h",
    price: "~$35/pers.",
    rating: 4.2,
    ratingCount: 75,
    variant: "rose",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "diner-croisiere-dj",
    title: "Dîner-croisière 3 services avec DJ",
    category: "anniversary",
    city: "Montréal",
    occasions: ["anniversaire", "saint-valentin", "date-night"],
    seasons: ["printemps", "ete", "automne"],
    steps: [
      "Repas 3 ou 5 services servi à table sur le fleuve",
      "DJ et dancefloor après le repas",
      "3 h 30 depuis le Vieux-Port",
    ],
    duration: "3h30",
    price: "~$180/pers.",
    rating: 4.6,
    ratingCount: 311,
    variant: "gold",
    forSingles: false,
    forCouples: true,
  },
  {
    id: "coucher-soleil-fleuve",
    title: "Coucher du soleil sur le Saint-Laurent",
    category: "nature",
    city: "Montréal",
    occasions: ["date-night", "anniversaire", "saint-valentin"],
    seasons: ["printemps", "ete", "automne"],
    steps: [
      "Excursion 1 h au coucher du soleil",
      "Champagne ou cocktails en option",
      "Ambiance calme, idéal pour une date romantique",
    ],
    duration: "1h",
    price: "~$50/pers.",
    rating: 4.4,
    ratingCount: 31,
    variant: "rose",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "mini-golf-vieux-port",
    title: "Mini-golf 18 trous · Vieux-Port",
    category: "adventure",
    city: "Montréal",
    occasions: ["1ere-date", "casual", "weekend"],
    seasons: ["printemps", "ete", "automne"],
    steps: [
      "18 trous en plein air le long du fleuve",
      "1 h 30 de jeu, super léger comme première date",
      "Bars et restos du Vieux-Port juste à côté",
    ],
    duration: "1h30",
    price: "~$23/pers.",
    rating: 5.0,
    ratingCount: 18,
    variant: "gold",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "croisiere-soiree-dj",
    title: "Croisière soirée avec DJ",
    category: "adventure",
    city: "Montréal",
    occasions: ["date-night", "weekend", "casual"],
    seasons: ["ete", "printemps", "automne"],
    steps: [
      "3 h 30 sur le fleuve en soirée",
      "DJ, dancefloor, bar à bord",
      "Vue nocturne sur la skyline",
    ],
    duration: "3h30",
    price: "~$92/pers.",
    rating: 4.1,
    ratingCount: 116,
    variant: "dark",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "aura-notre-dame",
    title: "Expérience AURA · Notre-Dame + croisière",
    category: "art-culture",
    city: "Montréal",
    occasions: ["anniversaire", "date-night", "saint-valentin"],
    seasons: ["all"],
    steps: [
      "Spectacle son et lumière AURA à la basilique Notre-Dame",
      "Enchainement avec une croisière commentée",
      "Un des combos les plus vendus à Montréal",
    ],
    duration: "1h30",
    price: "~$105/pers.",
    rating: 4.4,
    ratingCount: 119,
    variant: "gold",
    forSingles: false,
    forCouples: true,
  },
  {
    id: "cours-cuisine-chef-etoile",
    title: "Cours de cuisine avec un chef étoilé",
    category: "gastronomy",
    city: "Montréal",
    occasions: ["anniversaire", "date-night", "saint-valentin"],
    seasons: ["all"],
    steps: [
      "2 h 30 avec un chef formé par Michelin",
      "Vous cuisinez ensemble, puis dégustez sur place",
      "Vin d'accompagnement inclus",
    ],
    duration: "2h30",
    price: "~$179/pers.",
    rating: 4.3,
    ratingCount: 39,
    variant: "dark",
    forSingles: false,
    forCouples: true,
  },
  {
    id: "croisiere-electrique-petitgroupe",
    title: "Croisière bateau électrique · petit groupe",
    category: "nature",
    city: "Montréal",
    occasions: ["1ere-date", "2eme-date", "date-night"],
    seasons: ["ete", "printemps", "automne"],
    steps: [
      "45 min sur le fleuve en petit groupe",
      "Bateau silencieux, guide bilingue",
      "Parfait pour une date en début de soirée",
    ],
    duration: "45min",
    price: "~$40/pers.",
    rating: 4.6,
    ratingCount: 492,
    variant: "rose",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "musee-imaginarium",
    title: "Musée Imaginarium + menu dégustation",
    category: "art-culture",
    city: "Montréal",
    occasions: ["date-night", "anniversaire"],
    seasons: ["all"],
    steps: [
      "Exploration du musée Imaginarium",
      "Menu dégustation québécois enchainé après",
      "2 h combinées, culture + gastronomie",
    ],
    duration: "2h",
    price: "~$105/pers.",
    rating: 4.7,
    ratingCount: 3,
    variant: "gold",
    forSingles: false,
    forCouples: true,
  },
  {
    id: "spa-natureau-jour",
    title: "Spa Natur'Eau · journée depuis Montréal",
    category: "anniversary",
    city: "Montréal",
    occasions: ["anniversaire", "date-night", "saint-valentin", "weekend"],
    seasons: ["all"],
    steps: [
      "Transport aller-retour depuis Montréal inclus",
      "Journée complète au spa nordique Natur'Eau",
      "Bassins, saunas, foyers extérieurs",
    ],
    duration: "10h30",
    price: "~$168/pers.",
    rating: 4.9,
    ratingCount: 8,
    variant: "dark",
    forSingles: false,
    forCouples: true,
  },
  {
    id: "cours-danse-burlesque",
    title: "Cours de danse burlesque",
    category: "adventure",
    city: "Montréal",
    occasions: ["date-night", "casual", "anniversaire"],
    seasons: ["all"],
    steps: [
      "1 à 2 h en petit groupe privé",
      "Aucune expérience requise",
      "Sortie originale — pas la 15e visite de musée",
    ],
    duration: "1–2h",
    price: "~$67/pers.",
    rating: 5.0,
    ratingCount: 1,
    variant: "rose",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "standup-bar-clandestin",
    title: "Stand-up dans un bar clandestin",
    category: "adventure",
    city: "Montréal",
    occasions: ["1ere-date", "2eme-date", "casual", "date-night"],
    seasons: ["all"],
    steps: [
      "Spectacle de stand-up 2 h en français",
      "Ambiance speakeasy, adresse discrète",
      "Petit prix — parfait pour tester la chimie",
    ],
    duration: "2h",
    price: "~$11–14/pers.",
    rating: 4.5,
    ratingCount: 12,
    variant: "dark",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "suminagashi-encre-flottante",
    title: "Suminagashi · atelier d'encre flottante",
    category: "art-culture",
    city: "Montréal",
    occasions: ["date-night", "casual"],
    seasons: ["all"],
    steps: [
      "3 h d'atelier créatif en petit groupe",
      "Vous repartez avec vos œuvres sur papier",
      "Rare et calme, très bien pour une deuxième date créative",
    ],
    duration: "3h",
    price: "~$76–95/pers.",
    rating: 4.7,
    ratingCount: 8,
    variant: "gold",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "vieuxmtl-crepuscule-prive",
    title: "Vieux-Montréal au crépuscule · visite privée",
    category: "art-culture",
    city: "Montréal",
    occasions: ["date-night", "anniversaire", "weekend"],
    seasons: ["printemps", "ete", "automne"],
    steps: [
      "Visite privée à pied 2 h au coucher du soleil",
      "Guide francophone, ruelles et histoires",
      "Idéal juste avant un souper dans le Vieux-Port",
    ],
    duration: "2h",
    price: "~$151/pers.",
    rating: 5.0,
    ratingCount: 2,
    variant: "rose",
    forSingles: false,
    forCouples: true,
  },
  {
    id: "seance-photo-mtl-plateau",
    title: "Séance photo privée · centre-ville & Plateau",
    category: "anniversary",
    city: "Montréal",
    occasions: ["anniversaire", "date-night", "saint-valentin"],
    seasons: ["all"],
    steps: [
      "1 h avec un photographe pro, en couple ou en groupe",
      "Trajet centre-ville → Plateau",
      "Photos livrées après la session",
    ],
    duration: "1h",
    price: "~$50/pers. (200 $ / groupe)",
    rating: 5.0,
    ratingCount: 2,
    variant: "gold",
    forSingles: false,
    forCouples: true,
  },
  {
    id: "bars-horizon-tour",
    title: "Tour des bars de l'horizon",
    category: "adventure",
    city: "Montréal",
    occasions: ["date-night", "casual", "weekend"],
    seasons: ["all"],
    steps: [
      "3 h de visite guidée avec coupe-file",
      "3-4 rooftops différents avec vues panoramiques",
      "Un cocktail dans chaque bar",
    ],
    duration: "3h",
    price: "~$100–119/pers.",
    rating: 4.5,
    ratingCount: 82,
    variant: "dark",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "bijouterie-mileend",
    title: "Atelier bijouterie · Mile End",
    category: "art-culture",
    city: "Montréal",
    occasions: ["date-night", "anniversaire"],
    seasons: ["all"],
    steps: [
      "2 h le matin, tu conçois et repars avec ta pièce",
      "Cadre atelier créatif dans le Mile End",
      "Idée cadeau vivante pour un anniversaire",
    ],
    duration: "2h",
    price: "~$236/pers.",
    rating: 4.6,
    ratingCount: 6,
    variant: "gold",
    forSingles: false,
    forCouples: true,
  },
  {
    id: "mileend-gastro-tour",
    title: "Tour gastronomique · Mile-End",
    category: "gastronomy",
    city: "Montréal",
    occasions: ["date-night", "weekend", "casual"],
    seasons: ["all"],
    steps: [
      "3 h à pied dans le Mile-End",
      "7 dégustations dans 7 spots emblématiques",
      "Guide qui raconte l'histoire du quartier",
    ],
    duration: "3h",
    price: "~$123–137/pers.",
    rating: 4.6,
    ratingCount: 27,
    variant: "rose",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "jeantalon-petiteitalie-tour",
    title: "Marché Jean-Talon & Petite Italie · 8 dégustations",
    category: "gastronomy",
    city: "Montréal",
    occasions: ["date-night", "weekend", "casual"],
    seasons: ["printemps", "ete", "automne"],
    steps: [
      "3 h autour du marché Jean-Talon",
      "8 dégustations : produits locaux, fromages, pâtisseries italiennes",
      "Ambiance décontractée, idéal en journée",
    ],
    duration: "3h",
    price: "~$122/pers.",
    rating: 4.8,
    ratingCount: 12,
    variant: "gold",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "vieuxmtl-food-drinks",
    title: "Vieux-Montréal · gastronomie et boissons",
    category: "gastronomy",
    city: "Montréal",
    occasions: ["date-night", "weekend", "anniversaire"],
    seasons: ["all"],
    steps: [
      "3 h de visite à pied guidée",
      "Enchainement resto → bar → dessert",
      "Idéal pour un premier gros date-night qui pose l'ambiance",
    ],
    duration: "3h",
    price: "~$143–159/pers.",
    rating: 4.9,
    ratingCount: 112,
    variant: "dark",
    forSingles: false,
    forCouples: true,
  },
  {
    id: "cabane-a-sucre",
    title: "Visite guidée cabane à sucre + sirop d'érable",
    category: "winter",
    city: "Montréal",
    occasions: ["weekend", "date-night", "casual"],
    seasons: ["printemps", "hiver"],
    steps: [
      "Prise en charge depuis Montréal",
      "Cabane à sucre, dégustation de spécialités locales",
      "6 h — parfait pour la saison des sucres (mars-avril)",
    ],
    duration: "6h",
    price: "~$199/pers.",
    rating: 3.9,
    ratingCount: 42,
    variant: "gold",
    forSingles: true,
    forCouples: true,
  },
  {
    id: "cadillac-decapotable",
    title: "Visite guidée · Cadillac décapotable vintage",
    category: "anniversary",
    city: "Montréal",
    occasions: ["anniversaire", "saint-valentin", "date-night"],
    seasons: ["printemps", "ete", "automne"],
    steps: [
      "1 à 3 h en groupe privé (jusqu'à 5)",
      "Cadillac décapotable des années 60",
      "Coup de théâtre pour un anniversaire",
    ],
    duration: "1–3h",
    price: "~$155/couple (310 $ / groupe)",
    rating: 5.0,
    ratingCount: 80,
    variant: "gold",
    forSingles: false,
    forCouples: true,
  },
  {
    id: "parc-omega-safari",
    title: "Parc Oméga · safari loups & faune sauvage",
    category: "nature",
    city: "Montréal",
    occasions: ["weekend", "casual", "date-night"],
    seasons: ["printemps", "ete", "automne", "hiver"],
    steps: [
      "Depuis Ottawa (2 h de route de Montréal)",
      "Excursion privée d'une journée, prise en charge disponible",
      "Loups, bisons, orignaux en semi-liberté",
    ],
    duration: "5–7h30",
    price: "~$150/pers. (299 $ / couple)",
    rating: 5.0,
    ratingCount: 88,
    variant: "dark",
    forSingles: true,
    forCouples: true,
  },
];

export function starsString(rating: number): string {
  const full = Math.round(rating);
  return "★".repeat(full) + "☆".repeat(5 - full);
}
